### ISSUE TITLE
Onboarding link on the joining page is broken

### ISSUE THREAD

**Issue by ayust** [eve-val/www.of-sound-mind.com#11]
This one:
![image](https://user-images.githubusercontent.com/344766/97827456-358d3800-1c79-11eb-84ea-27fa4ba54e89.png)

Tries to point at https://www.of-sound-mind.com/onboarding.html which doesn't currently exist.

**Comment by kkrabfir** [comment]
@ayust I think we can close this, onboarding info is now inline.
